title: Vin Programming
description: > # this means to ignore newlines until "baseurl:"
  Win at Programming. Learn programming in Telugu.
permalink: ':title/'
baseurl: "/code" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: vinayakd1729 #if your site has a twitter account, enter it here

# Author Settings
author: Vinayak Kumar # add your name
author-img: vinayak.jpg # add your photo
about-author: Developer, Entrepreneur. I took this project to create quality programming lessons in Telugu. # add description
social-twitter: vinayakd1729 # add your Twitter handle
social-facebook: groups/356820909047722/ # add your Facebook handle
social-github: vinprogramming # add your Github handle
social-linkedin: in/vinayak-d-591987114/ # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier:  # add your discus identifier

# Tracker
analytics: UA-174917383-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
